name: xchange
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '^3.8.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  uuid: ^4.0.0
  flutter_webrtc: ^0.14.1
  flutter_p2p_connection: ^3.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700